/**
 * FeedbackEngine - Auto-generated feedback for integrity failures and errors
 * 
 * Generates diagnostic reports and provides easy submission mechanisms.
 */

// GitHub repo for issues
const GITHUB_REPO = 'EthnTuttle/fredco-audit';
const GITHUB_ISSUES_URL = `https://github.com/${GITHUB_REPO}/issues/new`;

/**
 * Integrity failure details
 */
export interface IntegrityFailure {
  filename: string;
  url: string;
  expectedHash: string;
  actualHash: string;
  expectedSize: number;
  actualSize: number;
  timestamp: number;
  source: 'cache' | 'network';
}

/**
 * Diagnostic report for feedback
 */
export interface DiagnosticReport {
  version: string;
  timestamp: string;
  userAgent: string;
  url: string;
  failures: IntegrityFailure[];
  environment: EnvironmentInfo;
}

/**
 * Environment information for debugging
 */
export interface EnvironmentInfo {
  platform: string;
  language: string;
  cookiesEnabled: boolean;
  onLine: boolean;
  storageAvailable: boolean;
  storageQuota?: {
    used: number;
    total?: number;
  };
}

/**
 * Collect environment information
 */
async function collectEnvironmentInfo(): Promise<EnvironmentInfo> {
  let storageQuota: { used: number; total?: number } | undefined;
  
  try {
    if (navigator.storage?.estimate) {
      const estimate = await navigator.storage.estimate();
      storageQuota = {
        used: estimate.usage ?? 0,
        total: estimate.quota,
      };
    }
  } catch {
    // Storage API not available
  }

  return {
    platform: navigator.platform,
    language: navigator.language,
    cookiesEnabled: navigator.cookieEnabled,
    onLine: navigator.onLine,
    storageAvailable: typeof indexedDB !== 'undefined',
    storageQuota,
  };
}

/**
 * Generate a diagnostic report
 */
export async function generateDiagnosticReport(failures: IntegrityFailure[]): Promise<DiagnosticReport> {
  const environment = await collectEnvironmentInfo();
  
  return {
    version: '1.0.0',
    timestamp: new Date().toISOString(),
    userAgent: navigator.userAgent,
    url: window.location.href,
    failures,
    environment,
  };
}

/**
 * Format report as Markdown for GitHub issue
 */
export function formatReportAsMarkdown(report: DiagnosticReport): string {
  const failuresList = report.failures.map(f => `
### ${f.filename}
- **Source**: ${f.source}
- **URL**: \`${f.url}\`
- **Expected Hash**: \`${f.expectedHash}\`
- **Actual Hash**: \`${f.actualHash}\`
- **Expected Size**: ${f.expectedSize.toLocaleString()} bytes
- **Actual Size**: ${f.actualSize.toLocaleString()} bytes
- **Timestamp**: ${new Date(f.timestamp).toISOString()}
`).join('\n');

  return `## Data Integrity Failure Report

**Generated**: ${report.timestamp}
**Page URL**: ${report.url}

### Failures
${failuresList}

### Environment
- **Platform**: ${report.environment.platform}
- **Language**: ${report.environment.language}
- **Online**: ${report.environment.onLine}
- **Storage Available**: ${report.environment.storageAvailable}
- **Storage Used**: ${report.environment.storageQuota?.used?.toLocaleString() ?? 'unknown'} bytes
- **Storage Total**: ${report.environment.storageQuota?.total?.toLocaleString() ?? 'unknown'} bytes

### User Agent
\`\`\`
${report.userAgent}
\`\`\`

---
*This report was auto-generated by the FCPS Data Playground integrity checker.*
`;
}

/**
 * Format report as JSON for download
 */
export function formatReportAsJson(report: DiagnosticReport): string {
  return JSON.stringify(report, null, 2);
}

/**
 * Create GitHub issue URL with pre-filled content
 */
export function createGitHubIssueUrl(report: DiagnosticReport): string {
  const title = encodeURIComponent(
    `Data Integrity Failure: ${report.failures.map(f => f.filename).join(', ')}`
  );
  
  const body = encodeURIComponent(formatReportAsMarkdown(report));
  const labels = encodeURIComponent('bug,data-integrity');
  
  return `${GITHUB_ISSUES_URL}?title=${title}&body=${body}&labels=${labels}`;
}

/**
 * Download report as file
 */
export function downloadReport(report: DiagnosticReport, format: 'json' | 'md' = 'json'): void {
  const content = format === 'json' 
    ? formatReportAsJson(report) 
    : formatReportAsMarkdown(report);
  
  const mimeType = format === 'json' ? 'application/json' : 'text/markdown';
  const extension = format === 'json' ? 'json' : 'md';
  const filename = `integrity-report-${Date.now()}.${extension}`;
  
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

/**
 * Show integrity failure dialog with feedback options
 */
export async function showIntegrityFailureDialog(failure: IntegrityFailure): Promise<'report' | 'download' | 'ignore'> {
  const report = await generateDiagnosticReport([failure]);
  
  // Create modal overlay
  const overlay = document.createElement('div');
  overlay.id = 'integrity-failure-modal';
  overlay.style.cssText = `
    position: fixed;
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
    background: rgba(0, 0, 0, 0.8);
    display: flex;
    align-items: center;
    justify-content: center;
    z-index: 10000;
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, monospace;
  `;

  const modal = document.createElement('div');
  modal.style.cssText = `
    background: #1a1a2e;
    border: 1px solid #e94560;
    border-radius: 8px;
    padding: 24px;
    max-width: 500px;
    width: 90%;
    color: #eee;
  `;

  modal.innerHTML = `
    <h2 style="margin: 0 0 16px 0; color: #e94560; font-size: 1.2rem;">
      Data Integrity Check Failed
    </h2>
    <p style="margin: 0 0 12px 0; color: #aaa; font-size: 0.9rem;">
      The file <strong style="color: #fff;">${failure.filename}</strong> failed integrity verification.
      This could indicate corrupted data, tampering, or a version mismatch.
    </p>
    <div style="background: #16213e; padding: 12px; border-radius: 4px; margin-bottom: 16px; font-size: 0.8rem;">
      <div style="display: flex; justify-content: space-between; margin-bottom: 8px;">
        <span style="color: #aaa;">Expected:</span>
        <code style="color: #00d9ff;">${failure.expectedHash.slice(0, 16)}...</code>
      </div>
      <div style="display: flex; justify-content: space-between;">
        <span style="color: #aaa;">Actual:</span>
        <code style="color: #e94560;">${failure.actualHash.slice(0, 16)}...</code>
      </div>
    </div>
    <p style="margin: 0 0 16px 0; color: #aaa; font-size: 0.85rem;">
      Please help us investigate by submitting a report:
    </p>
    <div style="display: flex; gap: 8px; flex-wrap: wrap;">
      <button id="btn-report-github" style="
        flex: 1;
        padding: 10px 16px;
        background: #238636;
        color: white;
        border: none;
        border-radius: 4px;
        cursor: pointer;
        font-size: 0.85rem;
        min-width: 120px;
      ">
        Report on GitHub
      </button>
      <button id="btn-download-report" style="
        flex: 1;
        padding: 10px 16px;
        background: #0f3460;
        color: white;
        border: 1px solid #333;
        border-radius: 4px;
        cursor: pointer;
        font-size: 0.85rem;
        min-width: 120px;
      ">
        Download Report
      </button>
      <button id="btn-ignore" style="
        flex: 1;
        padding: 10px 16px;
        background: transparent;
        color: #aaa;
        border: 1px solid #333;
        border-radius: 4px;
        cursor: pointer;
        font-size: 0.85rem;
        min-width: 120px;
      ">
        Continue Anyway
      </button>
    </div>
    <p style="margin: 16px 0 0 0; color: #666; font-size: 0.75rem; text-align: center;">
      The data will be re-fetched from the server.
    </p>
  `;

  overlay.appendChild(modal);
  document.body.appendChild(overlay);

  return new Promise((resolve) => {
    const cleanup = () => {
      document.body.removeChild(overlay);
    };

    modal.querySelector('#btn-report-github')?.addEventListener('click', () => {
      const issueUrl = createGitHubIssueUrl(report);
      window.open(issueUrl, '_blank');
      cleanup();
      resolve('report');
    });

    modal.querySelector('#btn-download-report')?.addEventListener('click', () => {
      downloadReport(report, 'json');
      cleanup();
      resolve('download');
    });

    modal.querySelector('#btn-ignore')?.addEventListener('click', () => {
      cleanup();
      resolve('ignore');
    });

    // Close on overlay click
    overlay.addEventListener('click', (e) => {
      if (e.target === overlay) {
        cleanup();
        resolve('ignore');
      }
    });

    // Close on Escape
    const handleKeydown = (e: KeyboardEvent) => {
      if (e.key === 'Escape') {
        document.removeEventListener('keydown', handleKeydown);
        cleanup();
        resolve('ignore');
      }
    };
    document.addEventListener('keydown', handleKeydown);
  });
}

/**
 * Track failures for batch reporting
 */
let pendingFailures: IntegrityFailure[] = [];

/**
 * Add a failure to the pending list
 */
export function trackIntegrityFailure(failure: IntegrityFailure): void {
  pendingFailures.push(failure);
}

/**
 * Get and clear pending failures
 */
export function getPendingFailures(): IntegrityFailure[] {
  const failures = [...pendingFailures];
  pendingFailures = [];
  return failures;
}

/**
 * Check if there are pending failures
 */
export function hasPendingFailures(): boolean {
  return pendingFailures.length > 0;
}
